AllCops:
  TargetRubyVersion: 2.3
Style/FrozenStringLiteralComment:
  Enabled: False
Metrics/LineLength:
  Max: 85
Metrics/MethodLength:
  Max: 20
Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
