source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'shotgun'
gem 'redis'
gem 'unicorn'
gem "rack-statsd", "~>0.1"
gem "statsd-ruby", "~>0.3"
gem "librato-rack"